[build]
  base = "."
  command = "yarn install --frozen-lockfile && cd app && yarn build"
  publish = "app/.next"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.19"
  NEXT_TELEMETRY_DISABLED = "1"

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Plugin configuration for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "nextjs"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
