[build]
  base = "app/"
  publish = "app/.next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect all API routes to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration
[functions]
  directory = "app/netlify/functions"
  node_bundler = "esbuild"

# Plugin configuration for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "nextjs"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "app/.next"
